version: '3.4'

x-common-variables:
  &common-variables
  MULTICAST_GROUP: 228.69.42.0
  MULTICAST_PORT: 7777
  BENCH_REQUEST_MSG: run_bench

services:
  bench-pickle:
    image: raphel/serialization-benchmark:latest-bench
    environment:
      <<: *common-variables
      SER_FORMAT: "Pickle"

  bench-json:
    image: raphel/serialization-benchmark:latest-bench
    environment:
      <<: *common-variables
      SER_FORMAT: "JSON"

  bench-xml:
    image: raphel/serialization-benchmark:latest-bench
    environment:
      <<: *common-variables
      SER_FORMAT: "XML"

  bench-yaml:
    image: raphel/serialization-benchmark:latest-bench
    environment:
      <<: *common-variables
      SER_FORMAT: "YAML"

  bench-msgpack:
    image: raphel/serialization-benchmark:latest-bench
    environment:
      <<: *common-variables
      SER_FORMAT: "MessagePack"

  bench-avro:
    image: raphel/serialization-benchmark:latest-bench
    environment:
      <<: *common-variables
      SER_FORMAT: "Avro"

  bench-proto:
    image: raphel/serialization-benchmark:latest-bench
    environment:
      <<: *common-variables
      SER_FORMAT: "ProtoBuf"

  bench-proxy:
    image: raphel/serialization-benchmark:latest-proxy
    environment:
      <<: *common-variables
      PORT: 2000
    ports:
      - 2000:2000/udp
